# Generated by Django 2.2.12 on 2020-04-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('department_head', models.BooleanField(default=False)),
                ('designation', models.CharField(max_length=150)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user_name', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('full_time', models.BooleanField(default=False)),
                ('part_time', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('dailyreport', models.TextField(default='', max_length=1000)),
                ('datetime', models.DateTimeField()),
                ('workhours', models.IntegerField(blank=True, null=True)),
                ('Feedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('uploadfile', models.FileField(blank=True, null=True, upload_to='static/files/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Login')),
            ],
        ),
    ]
