# Generated by Django 2.2.12 on 2020-04-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200425_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='Feedback',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('Daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Daily')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Login')),
            ],
        ),
    ]
